#index:
#    path: /
#    controller: Taskoo\Controller\DefaultController::index

file:
  path: /file/{filePath}
  controller: Taskoo\Controller\FileController::getFile
  requirements:
    filePath: .+